# mern-app/docker-compose.yml
version: '3.8'

services:
  # Backend Service (Express + Node.js)
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  # Frontend Service (React)
  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx default)
    depends_on:
      - backend

  # Database Service (MongoDB)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: